
const recipes = [
    {
        id: 1,
        title: "German lentil stew with spaetzle (Linsen mit Spätzle)",
        time: "40 min",
        tags: [
        ],
        description: "Lentils with spaetzle is a classic Swabian comfort dish made with lentils, vegetables, bacon, spaetzle, and sausages. Add vinegar at the end for better flavor and digestion. Let the lentils rest for 10 minutes so the spices blend. It tastes even better the next day, and paprika or nutmeg can add extra flavor.",
        image: "https://images.services.kitchenstories.io/6GydQsJ3NT3cx3LxqJRqNK7AqwM=/750x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3444_Final_4x3.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Peel and finely dice soup vegetables and the onion. Heat butter in a large pan. Sauté the onion cubes until translucent, then add remaining vegetables and bacon cubes and fry for approx. 5 min. Now sprinkle flour over it and stir carefully so that no lumps form.",
            image_url: "https://images.services.kitchenstories.io/wLOxv_9BTWfNrG8xNzWsAnruNSI=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3444_Step1_4x3.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Strain lentils in a sieve, rinse with cold water, and add them to pan. Add meat broth and bay leaves. Bring mixture to a boil once, then let simmer over medium heat for approx. 30 min. Until the lentils are soft. Stir occasionally and add a little more broth if necessary.",
            image_url: "https://images.services.kitchenstories.io/HhBSTuBf4Pzd75OlxjuJ72Lw0JE=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3444_Step2_4x3.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Prepare spaetzle according to package instructions in a pot of boiling water and then drain them. Heat sausages in water in a second pot. Season lentils with red wine vinegar, mustard, salt, pepper, and a little sugar and remove the bay leaves. Arrange Spätzle on plates, spoon the lentils over them, and serve with the sausages.",
            image_url: "https://images.services.kitchenstories.io/rClT2VBWwazGBdtVHbG1SSo8D1E=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3444_Step3_4x3.jpg",
          },
        ],
      },
      {
        id: 2,
        title: "Creamy mapo tofu udon",
        time: "20 min",
        tags: [
        ],
        description: "Creamy mapo tofu udon is a viral dish that’s quick and easy to make in about 20 minutes. Smooth blended tofu creates a creamy sauce for udon noodles, topped with flavorful fried ground meat. You can use beef, pork, chicken, or a vegan alternative, and season it with chili bean paste like doubanjiang or gochujang for a rich, spicy flavor.",
        image: "https://images.services.kitchenstories.io/9LNazBIG59jKOYEuCPgUnoSsEcA=/750x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3443_Mapo_tofu_udon.jpg_.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Peel and chop garlic finely. Cut scallions into fine rings and set some green parts aside for garnish. Heat oil in a pan and fry garlic and scallions until translucent. Then, add chili bean paste and fry for approx. 2 min more. Add ground beef and continue frying until thoroughly cooked for approx. 8 min. Deglaze with soy sauce and set aside.",
            image_url: "https://images.services.kitchenstories.io/0cB6bBOYNi6Y2RW5P4Wu9U0c1Nw=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3443_Mapo_tofu_udon_step_1.jpg_.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Boil water in a pot and cook udon noodles according to package instructions. Meanwhile, place silken tofu in a container, add a pinch of salt and miso. Then, blend until creamy.",
            image_url: "https://images.services.kitchenstories.io/ZPThe1-MskmQG-Ean9J3NRmB_VA=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3443_Mapo_tofu_udon_step_2.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Once udon noodles are done, assemble the mapo tofu udon plate. Place udon noodles on a plate, pour creamy tofu over it and add spicy ground beef mix on top. Garnish with scallion rings and chili crisp before serving.",
            image_url: "https://images.services.kitchenstories.io/09kITmCXL5oNm9oEDgXQ8qzQVBk=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3443_Mapo_tofu_udon_step_3.jpg_.jpg",
          },
        ],
      },
      {
        id: 3,
        title: "Cozy wild rice soup with sweet potato and mushrooms",
        time: "20 min",
        tags: [
        ],
        description: "This cozy wild rice soup is versatile and flavorful with balanced seasoning. If you don’t have Cajun seasoning, use paprika, oregano, thyme, and a pinch of cayenne. Creole seasoning also works well. For a milder taste, use smoked paprika and oregano, and add chili flakes if you want some heat.",
        image: "https://images.services.kitchenstories.io/3G89dV-Vx9w5G_y1lBdX4eFDMNk=/750x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3418_Final_4x3.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Cook wild rice according to package directions, drain and set aside. Dice onion and sweet potato. Chop garlic. Cube carrots. Slice celery sticks and mushrooms. Heat oil in a large pot and sauté onion, garlic, carrots, celery, and mushrooms for approx. 5 min. until lightly browned.",
            image_url: "https://images.services.kitchenstories.io/uT165ISDYdZy5f5ZyE8WddUEqko=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3418_Step1_4x3.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Add the vegetable broth. Add the bay leaf and Cajun seasoning and stir well. Bring the soup to a boil, then let it simmer gently over medium heat for approx. 15 min. until the vegetables are soft. Add the sweet potatoes during the last approx. 5 min. of cooking time.",
            image_url: "https://images.services.kitchenstories.io/l9sNeA-ujM_LWvHvyseIoZWIaaQ=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3418_Step2_4x3.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Thoroughly wash kale, remove thick stems and roughly cut leaves. Add coconut cream, kale and rice. Let soup simmer for approx. 5 min. more until kale is soft. Season soup to taste with salt and pepper and add some more Cajun seasoning if desired. Then, serve while hot.",
            image_url: "https://images.services.kitchenstories.io/vKxEqa-4oXVmxX2XSFiXc5-CEDU=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3418_Step3_4x3.jpg",
          },
        ],
      },
      {
        id: 4,
        title: "Orzo salad with harissa-roasted pumpkin and Brussels sprouts",
        time: "40 min",
        tags: [
        ],
        description: "This vegan orzo salad with roasted vegetables is colorful, flavorful, and full of different textures. Orzo is small pasta shaped like rice and is usually vegan because it's made from durum wheat semolina without eggs. The salad tastes best slightly warm but can also be prepared ahead of time like a regular pasta salad.",
        image: "https://images.services.kitchenstories.io/z9JtgsJbQTmJVxKJAFQC1le7YyU=/750x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R2785-photo-final-1_2.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Preheat the oven to 220°C/420 °F. Cut onion into approx. 1.5 cm/0.6 in. wedges. Trim Brussels sprouts, remove wilted leaves, and cut into quarters. Cut pumpkin into approx. 1.5 cm/0.6 in. cubes. Coarsely chop the parsley. Drain chickpeas, rinse thoroughly, and set aside.",
            image_url: "https://images.services.kitchenstories.io/aX3f1eJOgAwUNoxqnzzwfKuSUVw=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2785-photo-step-1.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "In a large bowl, mix harissa with some of the olive oil. Season with salt and pepper. Add the chopped vegetables and chickpea to the bowl. Mix well so they are coated in the harissa-oil mixture. Then place in a single layer on a baking sheet lined with parchment paper. Add unpeeled garlic cloves. Place in the oven and roast for approx. 20 min., turning the vegetables once halfway through. Remove from the oven when the vegetables are golden brown.",
            image_url: "https://images.services.kitchenstories.io/RCACYxxvTpqRwvYvc4dWKHMoyew=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3037-photo-step-2-3x4-crop-tight.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Meanwhile, in a large pot without oil, toast the almonds over medium heat until golden brown. Then take them out, roughly chop, and put them aside. Then, in the same pot, bring water to a boil and cook orzo pasta according to package directions until al dente.",
            image_url: "https://images.services.kitchenstories.io/WARdDW6AsyFxOQQECddlahikE_g=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3037-photo-step-3-4x3.jpg",
          },
          {
            step_id: 4,
            step_number: 4,
            instruction: "For the dressing, squeeze the insides of the roasted garlic cloves from the oven, when it's not too hot to handle, into the large bowl used in step 2. Add the remaining olive oil and mix well with a fork. Grate zest and juice lemon into the bowl. Add vinegar and maple syrup and mix well again. Season to taste with salt and pepper. Add oven vegetables, orzo pasta, toasted almonds, raisins, and parsley to the dressing. Mix until combined. Season again if necessary. Best served lukewarm.",
            image_url: "https://images.services.kitchenstories.io/nDaxjqDnAJuA4rlemRz5NVM3Ytc=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2785-photo-step-4.jpg",
          },
        ],
      },
      {
        id: 5,
        title: "Chewy chocolate chip cookies",
        time: "30 min",
        tags: [
        ],
        description: "Chewy chocolate chip cookies are soft, rich, and filled with sweet chocolate chips. They have a golden outside and a soft, chewy center, making them a classic and comforting treat perfect for any time.",
        image: "https://images.services.kitchenstories.io/FZtBo-KAliwTHJYiVq-RRuhu5yo=/828x0/filters:quality(85)/images.kitchenstories.io/recipeImages/ChewyChocolateChipCookies_Final.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Preheat the oven to 180°C (350°F) so it reaches the right temperature for baking. In a medium bowl, combine the flour, baking soda, and salt, then mix them well so the dry ingredients are evenly distributed before adding them to the rest of the cookie dough ingredients.",
            image_url: "https://images.services.kitchenstories.io/MF93eMjn0ynbYazkut-I4zFM8J8=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/12_08_ChewyChocolateChipCookies_step01.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "In another bowl, beat the softened butter, brown sugar, and vanilla sugar together until the mixture becomes light, fluffy, and pale in color. Mixing well at this stage helps create a smooth texture and ensures the sugar is fully incorporated into the butter.",
            image_url: "https://images.services.kitchenstories.io/fJ0J7t1ELn2ir4W3afPzkAEJefk=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/12_08_ChewyChocolateChipCookies_step02.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Add the eggs to the mixture one at a time, beating well after each addition until fully incorporated. This helps create a smooth, well-combined batter and ensures the eggs blend evenly with the other ingredients.",
            image_url: "https://images.services.kitchenstories.io/WcvzlusDykzY-akRx9ntnCrYktw=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/12_08_ChewyChocolateChipCookies_step03.jpg",
          },
          {
            step_id: 4,
            step_number: 4,
            instruction: "Add the flour mixture to the butter mixture and whisk gently until everything is well combined and forms a smooth dough. Then carefully fold in the chocolate drops, mixing just enough to distribute them evenly throughout the dough.",
            image_url: "https://images.services.kitchenstories.io/YpbaTOzHdja8F760oYr3NDJDkHc=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/12_08_ChewyChocolateChipCookies_step04.jpg",
          },
          {
            step_id: 5,
            step_number: 5,
            instruction: "Scoop dough onto a lined baking sheet, leaving enough space in between cookies. Flatten slightly with the back of the scoop. Bake in preheated oven for approx. 10 - 12 min. at 180°C/350°F until golden. Cookies should remain soft on the inside. Allow to cool for approx. 10 min. before serving.",
            image_url: "https://images.services.kitchenstories.io/4Z1Xud-5xT9xNIGRj0VAJefcMs8=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/12_08_ChewyChocolateChipCookies_step05.jpg",
          },
        ],
      },
      {
        id: 6,
        title: "Savoy cabbage carbonara with chestnut",
        time: "40 min",
        tags: [
        ],
        description: "This carbonara recipe shows how versatile the classic dish can be. It combines earthy savoy cabbage, sweet chestnuts, and rich Pecorino cheese for a deeper flavor. Remember the key carbonara rule: remove the pan from heat before mixing the eggs to keep the sauce creamy and smooth. The crispy Pecorino topping adds a salty crunch that makes this version even more special.",
        image: "https://images.services.kitchenstories.io/ktPjKdxYAhrxGC1Nnz9FLYyDd20=/828x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3397_Final_4x3.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Heat olive oil in a large pan. Add panko and toast until golden brown. Finely grate half the pecorino and mix with warm panko. Keep toasting until there is a crispy, golden brown pecorino crunch. Season with salt and pepper, remove from pan, and set aside. Wipe the pan clean.",
            image_url: "https://images.services.kitchenstories.io/2KEO2sH5THNMQtNsCDN-Br0lE8k=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3397_Step1_4x3.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Cook spaghetti according to package instructions until al dente. Once it's done, set aside some pasta water and drain the rest. Meanwhile, cut savoy cabbage into fine strips, roughly chop chestnuts, and finely chop peeled garlic.",
            image_url: "https://images.services.kitchenstories.io/SN02__R6yIWIdCU1XgtfkSObtpw=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3397_Step2_4x3.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "In the same large pan, heat some more olive oil and sauté savoy cabbage for approx. 5 - 7 min. until it's soft and lightly browned. Add garlic, chopped chestnuts, and briefly sauté again. Season with salt and pepper.",
            image_url: "https://images.services.kitchenstories.io/VFMTbTn3EI3hdUeiW0cWT0fP2sA=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3397_Step3_4x3.jpg",
          },
          {
            step_id: 4,
            step_number: 4,
            instruction: "Whisk egg yolks with remaining pecorino and pepper in a small bowl. Add cooked, still hot pasta to the pan. Then, add the egg mixture and pasta water to the still hot pasta. Mix quickly and evenly until you have a silky sauce. Add more pasta water if needed. Sprinkle pecorino crunch and chopped parsley on top and serve immediately.",
            image_url: "https://images.services.kitchenstories.io/Ejc23IIf95MrPvX6MRNIBA64jYY=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3397_Step4_4x3.jpg",
          },
        ],
      },
      {
        id: 7,
        title: "Pasta arrabiata",
        time: "20 min",
        tags: [
        ],
        description: "Arrabbiata is a classic Italian tomato sauce known for its spicy kick. Made with garlic, chili, and rich tomatoes, it has a bold and slightly “angry” flavor. Use good-quality ingredients for the best taste, adjust the chili flakes to control the heat, and garnish with parsley or basil for a touch of freshness.",
        image: "https://images.services.kitchenstories.io/b4Y6pYC9k9Liz-BzgcMJsTJhL0M=/828x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R1600-photo-final-1.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Season a pot of boiling water generously with salt. Add penne and cook until just shy of al dente, approx. 1 min. less than the package recommends. Drain, reserving approx. 1/4 cup (60ml) of pasta water.",
            image_url: "https://images.services.kitchenstories.io/XXdbnvH63ycV-9WndqunM32XDtQ=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1600-photo-step-1.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "While the pasta cooks, mince the garlic. Add olive oil to a large frying pan and add minced garlic and chili flakes. Sauté for approx. 3 min. over medium heat, then add tomato paste and canned chopped tomatoes. Let simmer for approx. 5 min.",
            image_url: "https://images.services.kitchenstories.io/KnXuVbgnqXnZI5Vr7Nu0cWkj628=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1600-photo-step-2.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Add reserved pasta water and cooked penne to the tomato sauce. Toss over medium heat until the pasta is coated in the sauce. Season with salt if needed. Serve immediately with freshly grated Pecorino cheese, a drizzle of olive oil, and parsley. Enjoy!",
            image_url: "https://images.services.kitchenstories.io/7wE7u2VdQaM-Ecvng_kaTtw4F7g=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1600-photo-step-3.jpg",
          },
        ],
      },
      {
        id: 8,
        title: "Cold noodle salad with peanut sauce",
        time: "20 min",
        tags: [
        ],
        description: "This soba noodle salad is a refreshing dish perfect for hot days. It’s served cold with a spicy peanut sauce, cucumber, red cabbage, and snap peas. You can add other raw vegetables and adjust the spice to your taste. A squeeze of lemon or chili crisp adds extra flavor, and the salad can be stored in the fridge for up to 3 days.",
        image: "https://images.services.kitchenstories.io/6zdWp2pMtyYHQAjocQoKCu6LFRQ=/828x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R2637-final-photo-_2.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Bring a pot of water to a boil over medium-high heat. In the meantime, slice the cucumber into thin strips. Thinly slice the scallions. Chop up the red cabbage. Slice the snow peas into bite-sized pieces. Cut the stems and leaves of the cilantro. Roughly chop the peanuts.",
            image_url: "https://images.services.kitchenstories.io/kVmOSn-qNtfzd72cgiqWEp32B-E=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2637-step-photo-_0.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Once the water boils, season with salt and cook the soba noodles according to package instructions. Drain and rinse with cold water until the noodles are completely cooled.",
            image_url: "https://images.services.kitchenstories.io/to7qZb9kkSrSJctKztPWekqPxEk=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2637-step-photo-_1.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "For the sauce, place the peanut butter, soy sauce, sesame oil, sugar and lemon juice in a large bowl. Mix well, then grate in the garlic with a fine grater. Mix again and thin out the sauce by adding cold water by the tablespoons until the desired consistency is reached. Add the noodles and all the vegetables and mix well. Garnish with peanuts, cilantro leaves and chilli oil if desired and serve. Enjoy!",
            image_url: "https://images.services.kitchenstories.io/-Ny4i28zp5v8vctx67qi0odxDWc=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2637-step-photo-_7.jpg",
          },
        ],
      },
      {
        id: 9,
        title: "Bang bang salmon bowl",
        time: "30 min",
        tags: [
        ],
        description: "After a long day, you're craving something quick and healthy-ish that still feels like a hug in a bowl? This bang bang salmon has you covered! The creamy-spicy sauce is all yours to play with - just add a little extra Sriracha if you want more of a fiery kick. When it comes to rice, it's totally up to your mood: sushi rice gives you that sticky, slightly sweet, authentic vibe; brown rice adds a nutty flavor and keeps you full for longer; and if you're after something fragrant, jasmine or basmati are perfect matches for the bold, savory salmon",
        image: "https://images.services.kitchenstories.io/Fvsa5KzTlElPrtKvapl825om1Fo=/828x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3373_Final_4x3.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Preheat the oven to 200 °C (top/bottom heat). In a large bowl, mix mayonnaise, sweet chili sauce, and Sriracha, then set aside. Cut the salmon into bite-sized pieces, season in a bowl with paprika powder, garlic powder, salt, and pepper, and mix well.",
            image_url: "https://images.services.kitchenstories.io/Q78ySCXBIrlKIWetlNEvvnc_kVU=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3373_Step1_4x3.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Line a baking sheet with parchment paper. Spread the seasoned salmon on top, drizzle with oil, and bake in the oven for approx. 8 - 10 min. until cooked through and easily flaked. Meanwhile, cook the rice according to package instructions. At the same time, slice the red cabbage into very thin strips and peel and grate the carrots.",
            image_url: "https://images.services.kitchenstories.io/EJUZDlkQKx2Pr-n6C7QZL5Cmw0Y=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3373_Step2_4x3.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Halve avocado and remove the pit, then slice. Slice the cucumber as well. Cook the edamame for approx. 2 - 3 min. according to package instructions, drain, remove from the pods and salt everything. Carefully mix the salmon with half of the bang bang sauce. Spoon rice into bowls and top with the vegetables and salmon. Garnish with coriander, the remaining sauce and sesame seeds, season to taste and serve.",
            image_url: "https://images.services.kitchenstories.io/H5dAFaVNCMCJO8VdTsTOqkUJQB4=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3373_Step3_4x3.jpg",
          },
        ],
      },
      {
        id: 10,
        title: "Halloumi tzatziki bowl with lemony orzo",
        time: "30 min",
        tags: [
        ],
        description: "This fresh Greek-inspired bowl with tzatziki, halloumi, and lemony orzo brings the taste of summer to your table. The orzo is mixed with lemon and spinach for a light, refreshing base, topped with grilled halloumi and a juicy tomato-cucumber salad. You can use store-bought tzatziki if needed, and add extra olive oil or crumbled feta for more flavor.",
        image: "https://images.services.kitchenstories.io/gLrf2KyIRJ34ppo5or_LOvgOquU=/828x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3372_Halloumi_tzatziki_bowl.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "Start the halloumi tzatziki bowl by preparing the orzo first. Finely mince garlic, zest half the lemon and halve red onion. Set one half aside and dice the other half. Heat some olive oil in a small pot and add diced onion and half of the garlic, frying for approx. 2 min. Then, add orzo and fry for approx. 2 min. more. Pour vegetable stock in, add pepper and oregano and let orzo simmer for approx. 10 - 15 min. stirring occasionally.",
            image_url: "https://images.services.kitchenstories.io/j2RB69g0bK4rDkg406yN_ng8SgY=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3372_Halloumi_tzatziki_bowl_step_1.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "While the orzo cooks, start making the tzatziki and grate half the cucumber into a bowl. To the same bowl, add greek yogurt, rest of finely minced garlic, olive oil, lemon juice, and salt. Mix until it’s creamy and well combined. For the rest of the bowl, slice remaining cucumber and halve cherry tomatoes. Cut the remaining onion half into thin rings.",
            image_url: "https://images.services.kitchenstories.io/licJXdgD3I_gJDGIuFz1oIF-ijg=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3372_Halloumi_tzatziki_bowl_step_2.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Cut halloumi into approx. 1 cm/0.4 in. thin slices and fry in a pan until both sides are golden brown for approx. 6 min. in total. Check on the orzo and mix in spinach leaves and lemon zest approx. 2 min. before it is done. Then, remove from heat and let cool a bit.",
            image_url: "https://images.services.kitchenstories.io/ZkTkzK2XYGc_2emRz3j6oLIdfz4=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3372_Halloumi_tzatziki_bowl_step_3.jpg",
          },
          {
            step_id: 4,
            step_number: 4,
            instruction: "Once the orzo cooled down, assemble the bowls. To a deep bowl add orzo, tomatoes, cucumber, red onion, olives, tzatziki, and halloumi. Sprinkle salt, pepper, and lemon juice. Serve with mint leaves on top.",
            image_url: "https://images.services.kitchenstories.io/7i8zMJ7Z291LA0U8GXq6kL0oafc=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3372_Halloumi_tzatziki_bowl_step_4.jpg",
          },
        ],
      },
      {
        id: 11,
        title: "Summery strawberry tiramisu",
        time: "25 min",
        tags: [],
        description: "This strawberry tiramisu is a fresh and summery twist on the classic dessert. It features creamy whipped mascarpone, layers of strawberries, and ladyfingers soaked in a fruity syrup made with balsamic vinegar, golden syrup, and water. The sweet and tangy flavors pair perfectly with the strawberries, making it a light and indulgent treat for strawberry season.",
        image: "https://images.services.kitchenstories.io/vwsS8hYVLFeClf3YQy44i84VH7k=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3322_Final_4x3.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Combine golden syrup, balsamic vinegar, and water in a small pot. Warm over medium heat and stir until it's all well combined. Let the mixture cool. Meanwhile, wash strawberries, remove the stems, and slice them thin.",
        image_url: "https://images.services.kitchenstories.io/mW3l_9zFI_q_bVkxE-AU1TpFTmI=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3322_Step1_4x3.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Separate the eggs. Beat egg yolks with honey and vanilla extract in a bowl until creamy, using a hand mixer. Gradually add mascarpone and mix until smooth. In a separate bowl, whip heavy cream until stiff and gently fold it into the mascarpone mixture.",
        image_url: "https://images.services.kitchenstories.io/kLChFiIMrbA-lcTqeKjMr_qxlOA=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3322_Step2_4x3.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Briefly dip ladyfingers one by one into the cooled syrup and cover the bottom of a glass dish with them. Spread half of the mascarpone cream over the ladyfingers and smooth it out. Spread half of the strawberry jam over the cream. Add another layer of syrup-dipped ladyfingers, spread with the remaining jam, and top with the remaining mascarpone cream.",
        image_url: "https://images.services.kitchenstories.io/2DUA40gbY6EQvgh6eF0EGra7ucA=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3322_Step3_4x3.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Top the Tiramisu with sliced strawberries. Cover and chill in the fridge, ideally overnight. Serve once it's chilled enough. Garnish with fresh mint if desired.",
        image_url: "https://images.services.kitchenstories.io/QEBgtLMtA_ON9mzI1RIqwBYaSLQ=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3322_Step4_4x3.jpg",
          },
        ],
      },
      {
        id: 12,
        title: "Chicken noodle soup",
        time: "50 min",
        tags: [],
        description: "This comforting chicken noodle soup is nostalgic, soothing, and full of flavor. Made with broth, chicken thigh, bacon, leek, root vegetables, and tender noodles, it's a hearty meal that can be ready in under an hour. It's a classic recipe perfect for making extra and freezing for later.",
        image: "https://images.services.kitchenstories.io/ZcY1g48KYL8Z43jjvAyNMUGW-Tc=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R1129-final-photo-1.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Dice bacon into small cubes. Peel and finely dice onion. Peel and dice potatoes and carrots. Remove tops and ends and slice celery and leeks.",
        image_url: "https://images.services.kitchenstories.io/lqGZNUkzKY3v9g7_vaWh6RwtYCY=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1129-step-photo-1a.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Melt butter in a large pot over medium-high heat. Add onion and bacon and fry for approx. 2- 3 min. Add chicken drumsticks and fry for approx. 3 - 5 min. Season with salt and pepper.",
        image_url: "https://images.services.kitchenstories.io/v4AJz2GJXUQEVMru5-z7XjzMcv0=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1129-step-photo-2.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Add the diced vegetables, bay leaves, and vegetable broth to the pot. Bring to a boil, cover with lid and reduce heat to medium. Let simmer for approx.15 min.",
        image_url: "https://images.services.kitchenstories.io/rs46_T3s_JJfjAua49LGBVX7vvY=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1129-step-photo-3a.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Remove chicken drumsticks from the pot. Set aside and allow to cool. In the meantime, add the egg noodles to the pot and cook, covered, for approx. 10 min.",
        image_url: "https://images.services.kitchenstories.io/HSgvW6jnkykwtmPm1Kv_saHe9N4=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1129-step-photo-4.jpg",
          },
          {
        step_id: 5,
        step_number: 5,
        instruction: "Once chicken drumsticks are cool enough to handle, remove the skin and discard. Remove the meat from the bone and shred or cut into bite-sized pieces. Add the chicken back into the pot. Season with salt and pepper to taste and serve the soup with a sprinkle of parsley.",
        image_url: "https://images.services.kitchenstories.io/c4WqUPl6dHjDcBejo2J46YE1wkU=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R1129-step-photo-5.jpg",
          },
        ],
      },
      {
        id: 13,
        title: "Smash burger",
        time: "20 min",
        tags: [],
        description: "This recipe shows how easy it is to make a USA-style smash burger at home. Cook the patties in a very hot cast iron pan to get a crispy crust and juicy center. Top with classic ingredients or customize with bacon, caramelized onions, or cheeses like blue or brie.",
        image: "https://images.services.kitchenstories.io/iCbnuVajG80ydVxZuQWGaSkBSsI=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R2121_smash_burger_title.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Peel and slice onion vertically. Wash the iceberg lettuce and finely shred. Drain the pickles. Mix mayonnaise, ketchup, and mustard in a small bowl. Halve the burger buns and toast to your liking. Cut parchment paper into 15 x 15 cm/6 x 6 in. squares for each patty.",
        image_url: "https://images.services.kitchenstories.io/DmuMEXzSj1ykXzdDebZqJ4Fa8yQ=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2121_smash_burger_step_1.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Heat the cast iron pan over high heat, then lightly brush with vegetable oil. Divide the ground beef into equal portions and shape into loose balls. Place patties in the pan in batches, being careful not to overcrowd. Cover each with a sheet of parchment paper, and flatten with a spatula until they are approx. 1 cm thick. Season with salt and pepper and cook over high for approx. 2 min. until the edges are crispy and brown.",
        image_url: "https://images.services.kitchenstories.io/lJaoKoHOAzUButy7miX6hemTROk=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2121_smash_burger_step_2.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Flip the patties, season with salt and pepper, and place a slice of cheese on each patty. Cook for another 1—2 min. Meanwhile, spread the sauce on both sides of the buns, then layer your lettuce on the bottom half. Next, stack the patties,onion, pickles, and the top of the bun. Serve immediately!",
        image_url: "https://images.services.kitchenstories.io/WZS2RcGv8T6LiXuYQ6eVtyq-LPc=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2121_smash_burger_step_3.jpg",
          },
        ],
      },
      {
        id: 14,
        title: "Molten chocolate cake",
        time: "45 min",
        tags: [],
        description: "Molten chocolate cake is a rich and indulgent dessert with a soft outer layer and a warm, gooey chocolate center. When baked just right, the cake opens to reveal a flowing chocolate filling, making it a perfect treat for chocolate lovers.",
        image: "https://images.services.kitchenstories.io/l6WZqFEJwOPCx4Z7WkEsqGgfbqQ=/1200x0/filters:quality(85)/images.kitchenstories.io/recipeImages/MoltenChocolateCake_FINAL.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Butter baking tins and dust with sugar. Make sure that it is evenly spread on the inside of the tins. Tap out excess sugar.",
        image_url: "https://images.services.kitchenstories.io/gYGMeoScfb-DyXitT1TpGZFSPKA=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step01.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Preheat oven to 200°C/400°F. Roughly chop couverture chocolate. Melt butter in a saucepan over medium heat. Add the chopped chocolate and melt together.",
        image_url: "https://images.services.kitchenstories.io/icrwkOnOPKl8O6GhySF1t75YtQ8=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step02.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "In a large bowl, beat the sugar, eggs, egg yolks, and salt using a mixer or whisk until the mixture becomes smooth, pale, and slightly thick. Mixing well helps incorporate air and creates a light texture for the batter.",
        image_url: "https://images.services.kitchenstories.io/Kv7L_BtkGtKNMuYDv-zkufgufo0=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step03.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Next, slowly add the melted chocolate to the egg mixture and stir gently until everything is fully combined and a smooth, rich batter forms. Make sure the chocolate is well incorporated to create an even and silky mixture.",
        image_url: "https://images.services.kitchenstories.io/vxSlRwRk0nauGO8H9GKF4CNuHNo=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step04.jpg",
          },
          {
        step_id: 5,
        step_number: 5,
        instruction: "Add the flour to the mixture and gently stir until it is fully incorporated. Mix just enough to combine everything and create a smooth, thick batter.",
        image_url: "https://images.services.kitchenstories.io/fglznXhVJFzbBL4gq86WZ5IrFig=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step05.jpg",
          },
          {
        step_id: 6,
        step_number: 6,
        instruction: "Now, divide the batter evenly among the buttered baking tins (approx. 4 cm high). Next, place the filled tins in the freezer for approx. 5 - 7 min.",
        image_url: "https://images.services.kitchenstories.io/Toxa7KwGamtVcGfdnH0qIymiG7c=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step06.jpg",
          },
          {
        step_id: 7,
        step_number: 7,
        instruction: "Bake cakes in a preheated oven at 200°C/400°F for approx. 8 - 10 min. Let stand for approx. 5 - 7 min. Carefully turn out the cakes, sprinkle with confectioner's sugar, and serve immediately. Whipped cream or ice cream go wonderfully with this treat.",
        image_url: "https://images.services.kitchenstories.io/yRri79oEmhzNfrck5WCd2TTutMU=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/04_01_WarmesSchokokuechleinMitFluessigemKern_step07.jpg",
          },
        ],
      },
      {
        id: 15,
        title: "Carbonara muffins",
        time: "35 min",
        tags: [],
        description: "Carbonara muffins are a creative twist on the classic Italian pasta dish. They combine eggs, cheese, pasta, and crispy bacon baked into savory muffins that are creamy inside and slightly crispy on the outside, making them perfect for a quick meal or snack.",
        image: "https://images.services.kitchenstories.io/PK5WpAQ2hQqS9CqS9z-qkKUjxoQ=/1200x0/filters:quality(85)/images.kitchenstories.io/recipeImages/C103-photo-final.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Preheat oven to 180°C/350°F (convection). Cook spaghetti in salted water according to package instructions. Heat some oil in a frying pan, then fry bacon cubes.",
        image_url: "https://images.services.kitchenstories.io/GpMk8nASnV2g6YnKK1rCXAM-EmQ=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/C103-photo-step-2.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Whisk eggs, heavy cream, and a part of the Parmesan cheese. Add fried bacon cubes. Season with salt and pepper. Add cooked spaghetti and mix.",
        image_url: "https://images.services.kitchenstories.io/ojuVGCSm4ESGiX2qEivzcyGXpkw=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/C103-photo-step-3.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Grease the muffin tin. Twirl spaghetti strands around a fork and place into muffin cups. Sprinkle with the remaining Parmesan cheese, then bake at 180°C/350°F (convection) for approx. 15 – 20 min.",
        image_url: "https://images.services.kitchenstories.io/D5NXqGtixKFAWY4aRea6USd8ZDs=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/C103-photo-step-4.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Remove the carbonara muffins from the oven and let them cool in the muffin tin for a few minutes. Then carefully lift them out, sprinkle with a little extra Parmesan or black pepper if you like, and serve warm.",
        image_url: "https://images.services.kitchenstories.io/4emnrQuwQhf45pEPvArfcS8bXMI=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/carbonara-muffins.jpg",
          },
        ],
      },
      {
        id: 16,
        title: "Breakfast burrito",
        time: "25 min",
        tags: [],
        description: "A breakfast burrito is a hearty and satisfying morning meal filled with ingredients like scrambled eggs, cheese and savory meats such as bacon or sausage, all wrapped in a warm tortilla. It's flavorful, filling, and perfect for a quick breakfast on busy mornings.",
        image: "https://images.services.kitchenstories.io/di54LYwOhI5dXmioNMsBy93iEy4=/1200x0/filters:quality(85)/images.kitchenstories.io/recipeImages/RP04_21_04_BreakfastBurito_TitlePicture.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Finely dice the bell pepper into small pieces. Thinly slice the onion into half rings, and finely chop the chives to add fresh flavor and color to the dish.",
        image_url: "https://images.services.kitchenstories.io/bXqGPm_ckz2Kq6J3bJg998XvRi0=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step01.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Using a box grater, roughly grate the cheese into small shreds. This helps it melt evenly and mix well with the other ingredients.",
        image_url: "https://images.services.kitchenstories.io/dLdPxrMHt6C7HU4L21ltbRWYaXU=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step02.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "In a large bowl, beat the eggs together with a few drops of Tabasco sauce until well combined. This adds a mild spicy kick and evenly distributes the flavor throughout the eggs.",
        image_url: "https://images.services.kitchenstories.io/T9pfScqa_8m8AQSRoMo2MgTsLUI=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step03.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Heat up butter in a frying pan and sauté onions over medium heat for approx. 1 - 2 minutes. Then, add the bell pepper, VIVA LA SPICE seasoning (if using), and continue to sauté for an additional 2 – 3 min.",
        image_url: "https://images.services.kitchenstories.io/efRuVGgvVLnwtIm5qnJrkJxzdFw=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step04.jpg",
          },
          {
        step_id: 5,
        step_number: 5,
        instruction: "Add eggs to the pan and continue to sauté, stirring occasionally, for approx. 3 - 5 min. Then, add the cheese and stir until melted.",
        image_url: "https://images.services.kitchenstories.io/2dLZ62xIHbssDhF4J6S4tNiiesg=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step05.jpg",
          },
          {
        step_id: 6,
        step_number: 6,
        instruction: "Place some of the eggs in the middle of the tortilla, taking care not to overfill. Sprinkle some chives on top. Fold tortilla in from the sides. Then, roll forward from bottom with thumbs until burrito is tightly rolled. Enjoy!",
        image_url: "https://images.services.kitchenstories.io/EkL_LjtLY3R8sB7Iuyp3lntheGU=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/RP04_21_04_BreakfastBurito_Step06.jpg",
          },
        ],
      },
      {
        id: 17,
        title: "Bok choy and crispy tofu stir fry",
        time: "20 min",
        tags: [],
        description: "This vegan weeknight dinner is quick and easy, ready in just 20 minutes. It's a light and refreshing meal for warm days and is packed with healthy carbs and protein.",
        image: "https://images.services.kitchenstories.io/y4JjeVL7fn3ziaOE-ySsuGI8eYY=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3057-photo-title-1-newforTK.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Peel and finely dice scallion and garlic. Deseed chili and slice into thin rings. Trim the ends off bok choy heads and slice each lengthwise into strips.",
        image_url: "https://images.services.kitchenstories.io/FL6sDPMh7cCUlheOiFvt07O1Fbc=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2236-photo-step-1.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "For the sauce, mix rice wine, soy sauce, water, and raw sugar in a small bowl. Pat tofu dry, then dice into bite-sized pieces. Add to a bowl with cornstarch and salt, and toss to coat.",
        image_url: "https://images.services.kitchenstories.io/qZdYTUfUZlNmtlTeJw-TMgulgRs=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2236-photo-step-2.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Heat toasted sesame oil in a frying pan over medium heat. Add tofu and sear for approx. 3 - 5 min., or until crisp. Remove from the pan and drain on paper towels.",
        image_url: "https://images.services.kitchenstories.io/Rsr8mJkDTpf5VBgHiZjX2Ej4Yug=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2236-photo-step-3.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Add bok choy, scallion, garlic, and chili to the same frying pan and sauté for approx. 2 - 3 min., then deglaze with sauce. Transfer crispy tofu back to the pan and toss to combine. Serve with cooked brown rice. Enjoy!",
        image_url: "https://images.services.kitchenstories.io/OZD4ISI4_XjeRyZ41dQilmDqzLs=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2236-photo-step-4.jpg",
          },
        ],
      },
      {
        id: 18,
        title: "Pancake tacos with candied bacon and scrambled eggs",
        time: "30 min",
        tags: [],
        description: "This fun breakfast recipe turns pancakes into soft, fluffy taco shells. Fill them with your favorite breakfast ingredients to create a tasty and creative way to start the day.",
        image: "https://images.services.kitchenstories.io/Q3Fe0myY_iiTAiPYHMIWAtQeG-g=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/extra_finals_0.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Preheat the oven to 180°C/350°F top/bottom heat. Combine flour, baking powder, sugar and salt in a large mixing bowl and set aside. Whisk eggs and milk in a small measuring cup. Then stir in half of the melted butter. Gently stir the milk mixture into the dry ingredients, but only enough to just mix everything together; a few small lumps are okay. If the batter seems too thick, add a little more milk.",
        image_url: "https://images.services.kitchenstories.io/gL5hiiqBCjmK1ylHG9pqwl83hl0=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2723-step-photo-_1.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Lay out the bacon strips on a baking tray lined with parchment paper. Brush the bacon with the maple syrup and season with pepper. Then bake in the preheated oven for approx. 15–20 min. until golden brown and crispy. Meanwhile, continue with the recipe. At the end of the baking time, remove the bacon from the tray and let it drain.",
        image_url: "https://images.services.kitchenstories.io/xQSozAxQZ06H-S-ydcFmcJUP7G4=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2723-step-photo-_2.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Melt half of the remaining butter in a large frying pan. Pour batter into the pan in batches and cook approx. 10 cm/ 4 in.-sized pancakes. Adjust heat as needed; generally, the first batch requires higher heat than the following batches. Flip pancakes after approx. 2–3 min., when bubbles rise to the surface and the bottom browns. Let the other side cook for approx. 1–2 min. more or until lightly browned. Take the pancakes out of the pan, stack them on a plate, and set aside.",
        image_url: "https://images.services.kitchenstories.io/7wutoPq-FX0WyeJISAsr58weJm4=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2723-step-photo-_3.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Cut chives into fine rings. Heat butter in a pan, whisk eggs with salt and pepper, and scramble them over low–medium heat. Stir in most of the cheese just before the eggs are done. Fold pancakes like tacos, fill with scrambled eggs, top with bacon and remaining cheese, garnish with chives and hot sauce, and serve immediately.",
        image_url: "https://images.services.kitchenstories.io/L4XQgeTNIhkO7U5KwV_OMCXPf3Q=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2723-final-photo-_1.jpg",
          },
        ],
      },
      {
        id: 19,
        title: "Fried chicken",
        time: "35 min",
        tags: [],
        description: "Fried chicken is a crispy and flavorful dish made by coating chicken in seasoned flour and frying it until golden brown. It has a crunchy outside and juicy, tender meat inside, making it a classic comfort food loved around the world.",
        image: "https://images.services.kitchenstories.io/AI95bm2qcUaAmL-Fwn0HHyesUyI=/1200x0/filters:quality(85)/images.kitchenstories.io/recipeImages/25_09_FriedChicken_TitlePicture.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Preheat oven to 200°C/400°F. In a small bowl, mix together garlic powder, onion powder, salt, pepper, and paprika.",
        image_url: "https://images.services.kitchenstories.io/DxeKRrLcCco07JULNhOz8B31P54=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/25_09_FriedChicken_Step01.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Carefully cut chicken legs in half at the joint. Rub them generously with spice rub, setting any excess spice rub aside.",
        image_url: "https://images.services.kitchenstories.io/ABrcCTIhWPaJSKGk9mKsUdrEnIE=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/25_09_FriedChicken_Step03.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "In a large bowl, whisk together egg, water, and Tabasco. In a separate large bowl, whisk together flour, baking powder, a pinch of salt, and the excess spice rub.",
        image_url: "https://images.services.kitchenstories.io/zVnqCIODyC_rL6Sl5LHaquTKhU8=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/25_09_FriedChicken_Step02.jpg",
          },
          {
        step_id: 4,
        step_number: 4,
        instruction: "Dip chicken pieces in the egg mixture until well coated on all sides. Lightly shake to remove excess liquid. Then dredge chicken in flour mixture until a thick and even crust is formed. Repeat these steps for a thicker crust if desired.",
        image_url: "https://images.services.kitchenstories.io/YtuEFZ9m2xsyIh2NgotU52HA1JU=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/25_09_FriedChicken_Step04.jpg",
          },
          {
        step_id: 5,
        step_number: 5,
        instruction: "Heat oil in a deep pan over medium-high heat. Fry chicken in batches for 3 - 5 minutes until golden and crispy, then bake at 200°C (400°F) for 10 - 15 minutes until cooked through. Serve with lemon wedges and dipping sauces.",
        image_url: "https://images.services.kitchenstories.io/aChQFn6gq319Nce6YU4gCVbyigI=/640x0/filters:quality(80)/images.kitchenstories.io/recipeStepImages/25_09_FriedChicken_Step05.jpg",
          },
        ],
      },
      {
        id: 20,
        title: "Spicy coconut-marinated grilled shrimp",
        time: "30 min",
        tags: [],
        description: "Spicy coconut-marinated grilled shrimp are juicy, flavorful, and slightly smoky. The shrimp are marinated in a creamy coconut mixture with spices and then grilled until tender, creating a delicious balance of spicy, savory, and lightly sweet flavors.",
        image: "https://images.services.kitchenstories.io/FyW6jQTFYawJf1zO55gPrKpfkpE=/1200x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R2045-photo-final-1.jpg",
        steps: [
          {
        step_id: 1,
        step_number: 1,
        instruction: "Finely dice ginger and garlic and add to a big bowl. Add coconut milk, chili paste, lime juice, brown sugar, and salt. Whisk in oil. Add shrimp, mix well, and let sit for at least 15 min. or up to 4 hrs.",
        image_url: "https://images.services.kitchenstories.io/MRT5v409KH5qQGC0NGIk7c16bjg=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2045-photo-step-1.jpg",
          },
          {
        step_id: 2,
        step_number: 2,
        instruction: "Remove shrimp from marinade. Add marinade to a small pot and bring to a boil. Reduce heat to medium heat and let reduce. Mix from time to time while simmering until creamy. Sauce should be thick enough to cover the back of a spoon.",
        image_url: "https://images.services.kitchenstories.io/KUJMJ5jUlJzdX-jUYBYLTZLYNJE=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2045-photo-step-2.jpg",
          },
          {
        step_id: 3,
        step_number: 3,
        instruction: "Grill shrimp on a very hot grill pan brushed vegetable oil over high heat. Serve with sauce, cilantro, and lime wedges. Enjoy!",
        image_url: "https://images.services.kitchenstories.io/WK7KwxKg9KlrtS6c6p4Glcl-TzQ=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2045-photo-step-4.jpg",
          },
        ],
      },
      {
        id: 21,
        title: "Spaghetti Bolognese",
        time: "45 min",
        tags: [
          { label: "Beef", color: "#C0651A" },
          { label: "Tomato", color: "#C0651A" },
        ],
        description: "Spaghetti Bolognese is one of the dishes from my childhood that stands out the most. Rich, saucey and incredibly flavorful. Hardly any other pasta dish is as well-known as this one",
        image: "https://images.services.kitchenstories.io/WmlcnmcFjLeDxrwIiV9zSGJkcl0=/640x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R150-final-photo-2.jpg",
        steps: [
          {
            step_id: 1,
            step_number: 1,
            instruction: "For the soffritto, peel and halve the onions and garlic. Peel and roughly chop the carrot. Roughly chop the celery. Add them to a food processor or blender and chop everything evenly until it is about as fine as the ground beef. Heat the olive oil in a large non-stick frying pan over low heat. Add the chopped vegetables and sauté for approx. 10-15 min. Stir regularly to make sure nothing burns.",
            image_url: "https://images.services.kitchenstories.io/wqvAi28OtHzLjtXX9AMhW2lJa2E=/750x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R150-step-photo-1.jpg",
          },
          {
            step_id: 2,
            step_number: 2,
            instruction: "Then add the ground beef to the pan and fry for another approx. 10-15 min. While frying, break up the meat with a cooking spoon. Season with salt and pepper.",
            image_url: "https://images.services.kitchenstories.io/Wl9Ij0QASGZ9RMz8thg72ZEYIIo=/750x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R150-step-photo-2.jpg",
          },
          {
            step_id: 3,
            step_number: 3,
            instruction: "Add the canned crushed tomatoes, tomato paste, salt, pepper and dried oregano. Simmer uncovered over medium heat for approx. 15-30 min. until the sauce has thickened.",
            image_url: "https://images.services.kitchenstories.io/t1yTaOY5AnDlledLnwv0ryIfRh4=/750x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R150-step-photo-3.jpg",
          },
          {
            step_id: 4,
            step_number: 4,
            instruction: "In the meantime, cook the spaghetti in plenty of boiling salted water according to package instructions until al dente. Drain the pasta and serve with the Bolognese sauce and grated Parmesan cheese.",
            image_url: "https://images.services.kitchenstories.io/I0Ji7dQ7j6D1Ce0sHtSq-VaRWyo=/750x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R150-step-photo-5.jpg",
          },
        ],
      },
    
      ,
]

